rem 모든 테이블 확인
SELECT * FROM tab;

rem 해당 테이블 내용 확인
SELECT * FROM 테이블명;

rem 테이블 구조 확인
DESC 'USR';

rem 테이블 확인
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE,
    DATA_DEFAULT
FROM 
    user_tab_columns
WHERE 
    TABLE_NAME = '회원'
ORDER BY 
    COLUMN_ID;

rem 테이블 확인
SELECT 
    utc.COLUMN_NAME, 
    utc.DATA_TYPE, 
    utc.DATA_LENGTH, 
    utc.NULLABLE,
    utc.DATA_DEFAULT,
    uc.CONSTRAINT_TYPE,
    uc.SEARCH_CONDITION
FROM 
    USER_TAB_COLUMNS utc
LEFT JOIN 
    (SELECT 
         acc.COLUMN_NAME, 
         ac.CONSTRAINT_TYPE, 
         ac.SEARCH_CONDITION
     FROM 
         USER_CONS_COLUMNS acc
     JOIN 
         USER_CONSTRAINTS ac 
     ON 
         acc.CONSTRAINT_NAME = ac.CONSTRAINT_NAME
     WHERE 
         ac.TABLE_NAME = '회원') uc
ON 
    utc.COLUMN_NAME = uc.COLUMN_NAME
WHERE 
    utc.TABLE_NAME = '회원'
ORDER BY 
    utc.COLUMN_ID;


SELECT * FROM SHOW_GRADE;
SELECT * FROM USR;
SELECT * FROM GENERAL_USR;
SELECT * FROM DESIGNER_USR;
SELECT * FROM FOLLOW;
SELECT * FROM PT_CATEGORY;
SELECT * FROM POST;
SELECT * FROM POST_WRITING;
SELECT * FROM POST_COMMENT;
SELECT * FROM POST_LIKE_IN;
SELECT * FROM DESIGN;
SELECT * FROM DESIGN_SIGN_UP;
SELECT * FROM DESIGN_BUY;
SELECT * FROM DESIGN_LIKE_IN;
SELECT * FROM SHOWROOM;
SELECT * FROM RESERVATION_TIME;
SELECT * FROM RESERVE;
SELECT * FROM DESIGNER_PAGE;
SELECT * FROM NEWS;
SELECT * FROM NEWS_WRITE;
SELECT * FROM NEWS_REGISTER;
SELECT * FROM NEWS_LIKE;
SELECT * FROM NEWS_COMMENT_WRITE;
SELECT * FROM COMPETITION;
SELECT * FROM SPONSOR;
SELECT * FROM RECRIUTMENT;
SELECT * FROM LIKE_COMP;
SELECT * FROM WRITE_RECRUIT;
SELECT * FROM UPLOAD_RECRUIT;
SELECT * FROM LIKE_RECRUIT;
SELECT * FROM APP_JOIN;
SELECT * FROM PRODUCT;
SELECT * FROM KEYWORD;
SELECT * FROM PRODUCT_LIKE;
SELECT * FROM REVIEW_WRITE;
SELECT * FROM DELIVERY_INFO;
SELECT * FROM PAYMENT_TYPE;
SELECT * FROM PURCHASE_STATE;
SELECT * FROM PROD_PURCHASE;
SELECT * FROM PUT_IN_CART;
SELECT * FROM REQUEST;
SELECT * FROM PURCHASE_CANCEL;
SELECT * FROM FASHINSHOW;
SELECT * FROM DESIGNER_TEAM;
SELECT * FROM PAR_BRAND;
SELECT * FROM BOOTH;
SELECT * FROM LIKE_FS;
SELECT * FROM INTEREST_FIELD;
SELECT * FROM NORMAL_PAR_F;
SELECT * FROM BELONG_TEAM;
SELECT * FROM REG_FOR_F;